from enum import Enum

class FailureCode(str, Enum):
    UNKNOWN = "UNKNOWN"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    NETWORK_ERROR = "NETWORK_ERROR"
    TIMEOUT = "TIMEOUT"
    RATE_LIMITED = "RATE_LIMITED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
